# Generated by Django 4.2.10 on 2024-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("stock", models.IntegerField()),
                ("price_sell", models.DecimalField(decimal_places=2, max_digits=5)),
                ("location", models.CharField(blank=True, max_length=50)),
                (
                    "price_bought",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("season", models.CharField(max_length=20)),
            ],
        ),
    ]
